### ISSUE TITLE
Doesnt work on Zig 0.10.0 upwards :(

### ISSUE THREAD

**Issue by darltrash** [vktec/znt#1]
What the title says. 

I'd love to see this ported to newer versions of Zig since it's my favourite way to handle entities here in zig world, and the alternative seems to be pretty intricate

**Comment by silversquirl** [comment]
Hey! Awesome to see someone else interested in this project :D

I've not worked on it for a while as you can see. If you feel like having a go at updating it I'd welcome a PR, otherwise I'll try and have a look within the next day or so!

**Comment by darltrash** [comment]
> Hey! Awesome to see someone else interested in this project :D
> 
> I've not worked on it for a while as you can see. If you feel like having a go at updating it I'd welcome a PR, otherwise I'll try and have a look within the next day or so!

I will try to understand it's code, it seems a bit complex considering it does some funky things with types, but I'll try my best :)

**Comment by darltrash** [comment]
![imagen](https://user-images.githubusercontent.com/38925212/208577082-afc88f32-397f-4657-975e-22b0a903b287.png)
uh oh...

**Comment by darltrash** [comment]
Here's my progress so far:
https://github.com/silversquirl/znt/compare/main...darltrash:znt:patch-1

**Comment by darltrash** [comment]
I feel like this might be useful, seems cool:

https://devlog.hexops.com/2022/lets-build-ecs-part-1/

**Comment by darltrash** [comment]
https://github.com/ziglang/zig/issues/12963

**Comment by silversquirl** [comment]
Sorry for the delay! Should be all fixed and working for latest Zig master :)
